services:
  netzet-test-api:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network
    env_file:
      - ${ENV_FILE_NAME}
    command: ${STARTUP_COMMAND}
    restart: always

networks:
  app-network:
    driver: bridge
